apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: sample-and-diagnosis-ufe
  namespace: wac-hospital-project
spec:
  image: lukasmichalcak/sample-and-diagnosis-ufe
  interval: 1m0s