apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: mglm-sample-and-diagnosis-test # napr. <pfx>-ambulance-wl
spec:
  title: Sample and Diagnosis, mglm # napr. "Zoznam čakajúcich <pfx>"
  description: "1. Technik vie generovať záznamy o odobratých vzorkách, po uložení ešte upravovať, mazať alebo označiť ako znehodnotené 2. Diagnostik vie ukladať konkrétne hodnoty a stanoviť diagnózu, predbežne ukladať alebo mazať a nakoniec spraviť finálny report" # napr. "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii"
  authors: "Maroš Guráň, Lukáš Michalčák" # Zadajte mená autorov
  azureLink: "https://mglm-sample-and-diagnosis-fpe2cehybadnd8bu.westeurope-01.azurewebsites.net/"
  frontendRepoUrl: "https://github.com/lukasmichalcak/sample-and-diagnosis-ufe"
  backendRepoUrl: "https://github.com/lukasmichalcak/sample-and-diagnosis-webapi"
  gitopsRepoUrl: "https://github.com/lukasmichalcak/sample-and-diagnosis-gitops"
