apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: mglm-sample-and-diagnosis-ufe-content
spec:
  microFrontend: mglm-sample-and-diagnosis-ufe
  # aplication context element
  element: mglm-sample-and-diagnosis-test-app
  attributes:
    - name: base-path
      value: /mglm-sample-and-diagnosis-test/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?mglm-sample-and-diagnosis-test(/.*)?$"