apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: lukasmichalcak/sample-and-diagnosis-ufe
  newName: lukasmichalcak/sample-and-diagnosis-ufe # {"$imagepolicy":  "wac-hospital-project:sample-and-diagnosis-ufe:name"}
  newTag: main.20260421.1224 # {"$imagepolicy": "wac-hospital-project:sample-and-diagnosis-ufe:tag"}
