apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: lukasmichalcak/sample-and-diagnosis-webapi
  newName: lukasmichalcak/sample-and-diagnosis-webapi # {"$imagepolicy":  "wac-hospital:sample-and-diagnosis-webapi:name"}
  newTag: main.20260507.2327 # {"$imagepolicy": "wac-hospital:sample-and-diagnosis-webapi:tag"}
- name: lukasmichalcak/sample-and-diagnosis-ufe
  newName: lukasmichalcak/sample-and-diagnosis-ufe # {"$imagepolicy":  "wac-hospital:sample-and-diagnosis-ufe:name"}
  newTag: main.20260507.2326 # {"$imagepolicy": "wac-hospital:sample-and-diagnosis-ufe:tag"}
