apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: mglm-sample-and-diagnosis-test
    wac-fiit.github.io/project: Sample and Diagnosis by Maroš Guráň and Lukáš Michalčák
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/mglm-sample-and-diagnosis-ufe
- ../../../apps/mglm-sample-and-diagnosis-webapi

patches:
- path: patches/sample-and-diagnosis-webapi.mongodb-auth.deployment.yaml

components:
- ../../../components/version-release
