apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital-project  # chceme tieto objekty umiestniť do `wac-hospital-project` namespace
                         # tento zapis preťaží hodnoty "namespace" vo všetkých objektoch
labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/mglm-sample-and-diagnosis-ufe

components:
- ../../../components/version-developers
